#!/bin/bash

#File: script

tree=$(tree -L 2 -tf --noreport -I '*~' --charset ascii $1 |
       sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g')

echo "${tree}" >> README.md
printf "${tree}"
